/**
 * Build seed.sql from base test prompts + generated demo catalog.
 * Also rebuilds catalog_tags and prompts_fts for fast reads/search.
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '../..');
const basePath = path.join(root, 'test-data/dummy-prompts.json');
const demoPath = path.join(__dirname, '../data/demo-prompts.json');
const outPath = path.join(__dirname, '../seed.sql');

const DEFAULT_AUTHOR = 'opm-demo';

function sqlEscape(value) {
  return String(value).replace(/'/g, "''");
}

/**
 * @param {string} filePath
 */
function loadPrompts(filePath) {
  if (!existsSync(filePath)) return [];
  return JSON.parse(readFileSync(filePath, 'utf8'));
}

/** Merge lists; demo entries override same id. */
const byId = new Map();
for (const p of loadPrompts(basePath)) {
  byId.set(p.uuid || p.id, { ...p, author: p.author || DEFAULT_AUTHOR });
}
for (const p of loadPrompts(demoPath)) {
  byId.set(p.uuid || p.id, p);
}
const prompts = [...byId.values()];

/** @type {Map<string, number>} */
const tagCounts = new Map();

const lines = [
  '-- Auto-generated by scripts/generate-seed.js — do not edit by hand',
  'DELETE FROM prompts_fts;',
  'DELETE FROM prompt_tags;',
  'DELETE FROM catalog_tags;',
  'DELETE FROM prompts;',
];

for (const p of prompts) {
  const id = p.uuid || p.id;
  const title = sqlEscape((p.title || '').slice(0, 200));
  const content = sqlEscape((p.content || '').slice(0, 32000));
  const tags = Array.isArray(p.tags) ? p.tags : [];
  const tagsJson = sqlEscape(JSON.stringify(tags));
  const author = sqlEscape(p.author || DEFAULT_AUTHOR);
  const publishedAt = sqlEscape(p.createdAt || new Date().toISOString());
  const imports = Number.isFinite(p.importCount) ? Math.max(0, Math.floor(p.importCount)) : 0;

  for (const tag of tags) {
    if (typeof tag !== 'string') continue;
    const key = tag.trim().toLowerCase();
    if (!key) continue;
    tagCounts.set(key, (tagCounts.get(key) || 0) + 1);
    lines.push(
      `INSERT INTO prompt_tags (prompt_id, tag) VALUES ('${sqlEscape(id)}', '${sqlEscape(key)}');`
    );
  }

  lines.push(
    `INSERT INTO prompts (id, title, content, tags, author, published_at, import_count) VALUES ('${sqlEscape(id)}', '${title}', '${content}', '${tagsJson}', '${author}', '${publishedAt}', ${imports});`
  );
  lines.push(
    `INSERT INTO prompts_fts (id, title, content) VALUES ('${sqlEscape(id)}', '${title}', '${content}');`
  );
}

for (const [tag, count] of [...tagCounts.entries()].sort((a, b) => a[0].localeCompare(b[0]))) {
  lines.push(`INSERT INTO catalog_tags (tag, count) VALUES ('${sqlEscape(tag)}', ${count});`);
}

writeFileSync(outPath, `${lines.join('\n')}\n`, 'utf8');
console.log(
  `Wrote ${prompts.length} prompts, ${tagCounts.size} tags, FTS rows to ${outPath}`
);
