name: Prepare Production Manifest

on:
  push:
    branches:
      - main

jobs:
  update-manifest:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Grant write permission

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update manifest.json
        run: |
          # Your script to update the manifest.json
          echo "Updating manifest.json"

      - name: Copy production manifest
        run: cp src/manifest.prod.json src/manifest.json

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add manifest.json
          git commit -m "Update manifest.json to production"
          git push